### ISSUE TITLE
`consumeOne` method not implemented — password reset broken with `better-auth >=1.7.0`

### ISSUE THREAD

**Issue by rasyidly** [zenstackhq/zenstack#2820]
## Description

The `zenstackAdapter` does not implement the `consumeOne` method, which became **required** in `better-auth@1.7.0`. This causes a `BetterAuthError` when users attempt to reset their password.

## Error

```
BetterAuthError: Adapter "zenstack" must implement consumeOne for atomic single-use credential consumption.
    at factory.mjs:699:68
```

## Steps to Reproduce

1. Set up a project with `better-auth@^1.6.26` (resolves to `1.7.x`) and `@zenstackhq/better-auth@3.9.2`
2. Configure email/password with `sendResetPassword`
3. Request a password reset email
4. Click the reset link and submit the new password
5. The error above is thrown

## Expected Behavior

Password reset completes successfully. The `consumeOne` method should atomically find and delete the single-use token from the verification table.

## Environment

- `@zenstackhq/better-auth`: `3.9.2`
- `better-auth`: `1.7.1`
- Provider: PostgreSQL

## Notes

- `better-auth@1.7.0` introduced `consumeOne` as a **required** adapter method for atomic single-use credential consumption (used for password reset tokens and potentially email verification tokens).
- The `peerDependencies` allow `better-auth: "^1.3.0"`, but the adapter does not work with `1.7.x`.
- As a workaround, I've pinned `better-auth` to `~1.6.26` to avoid the breaking change.
- This likely affects all versions of `@zenstackhq/better-auth`.

## Workaround

Pin `better-auth` to `~1.6.26` in your `package.json`:

```json
"better-auth": "~1.6.26"
```
```
